name: Deploy to FTP

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.revolutionresearch.com.au
          username: ${{ secrets.BEAUTIFUL_REVOLUTION_USER }}
          password: ${{ secrets.BEAUTIFUL_REVOLUTION_PW }}
          local-dir: client/build/
          server-dir: /home1/cp421265/public_html/beautifulrevolution.com.au/
